version: '3.1'
services:

  postgres:
    image: postgres
    #    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-data:/C/volumes
volumes:
  db-data: